### ISSUE TITLE
"npm run tnpm-dep" occur error

### ISSUE THREAD

**Issue by dushao103500** [salt-ui/saltui#1]
I have the problem when i start the code `npm run tnpm-dep`：

	events.js:160
      throw er; // Unhandled 'error' event
      ^

	Error: spawn tnpm ENOENT
	    at exports._errnoException (util.js:1022:11)
	    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	    at onErrorNT (internal/child_process.js:359:16)
	    at _combinedTickCallback (internal/process/next_tick.js:74:11)
	    at process._tickCallback (internal/process/next_tick.js:98:9)
	    at Module.runMain (module.js:606:11)
	    at run (bootstrap_node.js:394:7)
	    at startup (bootstrap_node.js:149:9)
	    at bootstrap_node.js:509:3 
some idea?

**Comment by gbk** [comment]
tnpm is not in your $PATH

**Comment by eternalsky** [comment]
if `npm run tnpm-dep` fail to work, just run `tnpm i` instead.
